### ISSUE TITLE
Create easy-to-manage package for LLVM bitcode

### ISSUE THREAD

**Issue by chrisseaton** [graalvm/sulong#137]
Languages which can load extensions, like Ruby, are often build around a model of `.so` files being on a load path and being dynamically loaded. I'd like to be able to provide something similar for Sulong.

So what I propose is a linker command that produces a `.su` file - a Sulong library file - which is a zip file with LLVM bitcode in it, and a manifest that specifies which libraries it depends on.

Then where Ruby normally allows you to load a `.so` file, we do exactly the same thing with our `.su` files.

Linking bitcode files into a `.su` and specifying which libraries to load when that library is loaded would look like this:

```
$ mx su-link test.su -lz test.ll
```

You could then directly run the `test.su` file:

```
$ mx su-run test.su
```

Or you can load your Sulong library like you would a native library:

```
$ mx su-run -ltest main.ll
```

Sulong would automatically detect the difference between a native library and a Sulong library, and in the latter case it would just load all the dependent libraries and then all the bitcode in the zip file.

Why not just link everything into a single big bitcode file for your library? Because we need somewhere to list dependent libraries. If a Ruby extension needs `zlib` then I need to say that somewhere.

I've started working on this in https://github.com/graalvm/sulong/compare/master...chrisseaton:su-files

Let me know if you think I'm heading down the wrong path.

**Comment by mrigger** [comment]
I agree that an own file format makes sense. I looked through the code and it looks fine to me. Here a few comments/thoughts:
- We could also support to accept several bitcode files by `su-link `and link the bitcode files together by using [llvm-link](http://llvm.org/docs/CommandGuide/llvm-link.html).
- Maybe we should follow the convention of GCC and Clang to specify the output file with` -o`? Then we could invoke the link command with either `mx su-link -o test.su -lz test.ll` or `mx su-link -lz test.ll -o test.su`?
- I think we should keep the manifest file extensible, so that we can add flags when loading libraries.
