### ISSUE TITLE
Fix cross-module managed global variables

### ISSUE THREAD

**Issue by chrisseaton** [graalvm/sulong#403]
At the moment each IR file creates a new `LLVMGlobalVariableStorage` for each global variable it knows about. This breaks the system for storing managed objects in global variables, as the storage and specialisation information for that lives in `LLVMGlobalVariableStorage`. We need to share `LLVMGlobalVariableStorage` objects globally.

**Comment by chrisseaton** [comment]
I found the `CorrectExternalVariableLinking` option - why is this `false` by default @mrigger? Setting it to true doesn't fix this issue though.

**Comment by mrigger** [comment]
The option should fix the issue that the Graal NFI is used to resolve a global variable, even when it is defined in another source file (see #395). I think the cross-module `LLVMGlobalVariableStorage` sharing could build on this change.

The option makes start-up slower, since it iterates over the global variables of the bitcode libraries and the source to be parsed. Since support for it is currently rarely needed, I disabled it by default until we have finished the integration of the binary parser.

**Comment by chrisseaton** [comment]
I'm sure it can be simple than this. Could we make it lazy? When you see a global you create an `LLVMGlobalVariableStorage`, which does no native lookup up front. If you see the place where the global is defined (as opposed to declared) you mark the global storage object. When all your files are loaded and you start to run the program and first use a global variable, it could then look for the native symbol if it hasn't been marked as defined.

**Comment by mrigger** [comment]
Yes, that would be possible and more efficient. I decided for the other implementation since it less complex.

**Comment by chrisseaton** [comment]
We already solve this problem for functions don't we? I think we should have a global variable registry, like we have a function registry. I'll do a PR to suggest that.

**Comment by chrisseaton** [comment]
Fixed by #417
