### ISSUE TITLE
Refactoring LLVM Options

### ISSUE THREAD

**Issue by grimmerm** [graalvm/sulong#533]
Currently, LLVMBaseOption is an enum, all its values are accessed by Sulong code via LLVMBaseOptionFacade.
My question is if we can remove the Facade and have LLVMOption as a class with static final fields for all options.
This refactoring would keep the "print all options" feature.

Also, while I understand most of the options, there are a few where I would like to ask who is using them and why they were added. Maybe we can reduce the number of options by identifying unused ones.

DEBUG
if we were able to test Sulong using mx unittest, this option not required anymore, is that correct?

REMOTE_TEST_BOOT_CLASSPATH
REMOTE_TEST_CASES_AS_LOCAL
if we use mx to build testsuites, and can avoid remote execution, this option is not required anymore, is that correct?

LIFETIME_TEST_GENERATE_REFERENCE_OUTPUT
when the new bitcode parser is integrated, we can check-in reference output as well as the LLVM IR files for testing, right?
Do we need this option after that change?

TEST_BINARY_PARSER
this option will go away once the new parser is here, right?

LLVM_VERSION
please explain

NODE_CONFIGURATION
please explain

PROJECT_ROOT
this is used for test discoverage and tool discoverage, right?
once all of this happens on mx side, we could remove this option, right?

OPTIMIZATIONS_DISABLE_SPECULATIVE
OPTIMIZATION_SPECIALIZE_EXPECT_INTRINSIC
OPTIMIZATION_VALUE_PROFILE_MEMORY_READS
OPTIMIZATION_VALUE_PROFILE_FUNCTION_ARGS
OPTIMIZATION_BRANCH_PROBABILITIES
OPTIMIZATION_INTRINSIFY_C_FUNCTIONS
OPTIMIZATION_INLINE_CACHE_SIZE
OPTIMIZATION_LIFE_TIME_ANALYSIS
why do we want to configure optimizations on this level?

**Comment by mrigger** [comment]
- `DEBUG` is used by `LLVMLogger#info` which is used by some other methods. I think we should keep a notion of debug output, either through this flag or by other means.
- `REMOTE_TEST_BOOT_CLASSPATH` and `REMOTE_TEST_CASES_AS_LOCAL` can be removed as you said.
- `LIFETIME_TEST_GENERATE_REFERENCE_OUTPUT` is still useful if we need to regenerate the reference output, e.g., when we change the lifetime analysis. However, we could remove the flag and instead provide a new class that generates the output when executed.
- `TEST_BINARY_PARSER` can be removed when we replaced the text parser as you said.
- `LLVM_VERSION`: \cc @pointhi
- `NODE_CONFIGURATION` allows to choose which node factory facade is selected (see [EXTENDING.md](https://github.com/graalvm/sulong/blob/master/docs/EXTENDING.md) for details).
- `PROJECT_ROOT`: I think we can remove this option when the compilation logic happens on the mx side, since we then do not longer need to reference directories in other projects.
- `OPTIMIZATION*`: I introduced this options in case we want to evaluate the influence of certain optimizations to the overall performance. In practice, I have never used them so it would be okay for me to have them removed.

**Comment by grimmerm** [comment]
OK, thx for clarification of options - that all makes sense to me.
Can we agree on:
Removing
REMOTE_TEST_BOOT_CLASSPATH, REMOTE_TEST_CASES_AS_LOCAL, TEST_BINARY_PARSER, LLVM_VERSION (? \cc @pointhi ), PROJECT_ROOT, OPTIMIZATION* 
step-by-step once all prerequisites are fulfilled?

What about refactoring (e.g. Facade)?

**Comment by mrigger** [comment]
I think we can remove the facade as you suggested.

**Comment by pointhi** [comment]
For ```LLVM_VERSION```, I want to say we have differences in the bitcode parser for LLVM3.2 and LLVM3.8. There is currently no detection of the LLVM Version inside sulong, so I added this option some time ago to simplify testing of the different code paths. Those differ quite a bit for the metatdata parser when changing from 3.2 to 3.8.
