### ISSUE TITLE
Expose `GlobalConstant` in the node factory facade

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#557]
Until now, the node factory facade has not discriminated between global variables and constant global variables (which cannot be modified during runtime). We could take advantage of this knowledge for additional optimizations. Thus, we should expose `GlobalConstant`s in the node factory facade. There is already a

```java
    Object allocateGlobalVariable(GlobalVariable globalVariable);
```
method to which we could add an additional parameter. However, after looking at the inheritance tree of the bitcode parser it would probably be better to just expose another method

```java
   Object allocateGlobalConstant(GlobalConstant globalConstant);
```

The text parser would not use this method, since it treats global constants and variables in the same way. However, it would be beneficial to have this additional information when using the binary parser.

@jkreindl or @pointhi could you have a look at that?

**Comment by jkreindl** [comment]
Both @pointhi and I already ran into problems with globals. I planned for that to be the last thing I would work on to integrate the binary parser because I think having everything else working will make this much easier.

Differentiating between global variables and constants seems like a good idea though. If this can still wait for a bit I will include this change when I work on globals.
