### ISSUE TITLE
Reduce # of packages in Sulong

### ISSUE THREAD

**Issue by grimmerm** [graalvm/sulong#568]
The current project dependencies in Sulong are:
```
             llvm.runtime
                  I
             llvm.types
             /        \
llvm.parser         llvm.nodes
            \          /
         llvm.parser.base
                  I
             llvm.context
             /         \
llvm.nodes.impl llvm.parser.bc.impl
           I             I
llvm.asm.amd64           I
           I             I
llvm.parser.factories    I
                   \     I
                      llvm
```
I would like to reduce the number of projects because some of them do not seem to be necessary and only contain a few classes.
What is your opinion on:
- merging llvm.parser and llvm.parser.base
- rename llvm.parser.bc. impl to llvm.parser.bc
- rename llvm.nodes to llvm.nodes.api (same naming convention as Truffle projects use)
- rename llvm.nodes.impl to llvm.nodes.basic

The result could look like:
```
             llvm.runtime
                  I
             llvm.types
                  I
            llvm.nodes.api
                  I
              llvm.parser
                  I
             llvm.context
             /         \
llvm.nodes.basic    llvm.parser.bc
           I             I
llvm.asm.amd64           I
           I             I
llvm.parser.factories    I
                   \     I
                      llvm
```

Thanks for the input.

**Comment by mrigger** [comment]
- I think it is okay to rename API projects to end with `.api` and remove the `.impl` ending in implementation projects.
- I agree that the number of projects can (and should be) reduced. `llvm.parser.base` was only a temporary project that contains/contained common parser code shared between the textual and binary parser. Once the textual parser is removed, we should remove it again (or before if it is already possible).
- I think we should rename `nodes.impl` to `nodes`, since the project contains almost all the nodes. If you want, we can also rename it to `nodes.core` to be in line with the `graal-core` naming convention.

**Comment by grimmerm** [comment]
Can we merge llvm.parser.factories and llvm.as.amd64  into llvm.nodes?
Is there a good reason to have 3 distinct projects?

**Comment by grimmerm** [comment]
https://github.com/graalvm/sulong/pull/626
