### ISSUE TITLE
Are AVX instructions supported?

### ISSUE THREAD

**Issue by richardstartin** [graalvm/sulong#777]
I might not have understood the code but I don't see any vector instructions in [AsmFactory](https://github.com/graalvm/sulong/blob/master/projects/com.oracle.truffle.llvm.asm.amd64/src/com/oracle/truffle/llvm/asm/amd64/AsmFactory.java). Is this the right place to look for supported instructions?

**Comment by grimmerm** [comment]
That is the code for our inline assembly interpreter.
Sulong's LLVM IR interpreters are dynamically compiled using the Graal compiler.

**Comment by richardstartin** [comment]
I will try it out, but if I can produce some LLVM IR with clang (which is great because its optimiser produces _exactly_ the assembly I want for my little experiment) then I should be able to execute it no matter what, is that the end goal for this?

Is there some kind of support for handwritten assembly snippets via this assembly interpreter you mention? If I get that working I can contribute some documentation.

**Comment by grimmerm** [comment]
I'm not sure I fully understand your use-case.

Sulong is an LLVM IR interpreter that runs LLVM IR (and simple inline assembly) on a *JVM*.
We are using Graal to dynamically compile the LLVM IR interpreter to machine code - you have no control over the machine code that's being generated by Graal.

**Comment by richardstartin** [comment]
Ideally I would like to execute a snippet of assembly (using instructions you seem not to currently support e.g. VMAXPD, VXORPD) on a _JVM_. Failing that, I would write the code in C++ using Intel AVX intrinsics and ask clang to produce LLVM IR, which I expect to pass into sulong. My end goal is to understand if it's possible to implement SIMD intrinsics for the _JVM_. Am I barking up the wrong tree?

**Comment by richardstartin** [comment]
I may have missed the point of this project - feel free to close this issue. Thanks for your input.

**Comment by rschatz** [comment]
> My end goal is to understand if it's possible to implement SIMD intrinsics for the JVM.

If your goal is to inject custom assembly code in the compiled output of a Java program, then you might want to look at the `graal` project (https://github.com/graalvm/graal/tree/master/compiler). That is the compiler that generates the machine code that will be actually executed when running Java and Truffle programs. It should be relatively easy to introduce custom nodes in the Graal IR that inject arbitrary assembly snippets.

**Comment by mikehearn** [comment]
Richard, HotSpot C2 at least does auto-vectorise and will use AVX instructions but I believe Graal does not. So although you can implement AVX in software such that Sulong can run such software, it'd not see the performance improvements you'd hope for unless some work is done on the Graal side too I guess.

**Comment by richardstartin** [comment]
@mikehearn C2 does indeed autovectorise, in fact I have debugged what it does and does not do fairly exhaustively over several months, and project panama will at some point in the future generate very tight code. However, C2 can't vectorise population counts (clang does - see [this paper](https://arxiv.org/pdf/1611.07612.pdf)) - I want to be able to execute that assembly snippet.

Thanks for the heads up on graal and vectorisation.

**Comment by chrisseaton** [comment]
@richardstartin having spoken to you on Twitter and seen your blog post, I think what you want to do is emit specific assembly instructions? If so I would recommend writing a method and then extending Graal to intrinsify it.

Otherwise you could use Graal directly to create a method with your instructions in it.

In both cases you'd need to extend Graal's assembler to have the instructions you want if you can't find them, but I think they may be there - just hidden behind an abstraction which gives one interface for emitting arithmetic, with an option to use SIMD, which then uses AVX.

You could also possibly use Graal directly and just emit the bytes yourself, so not extending Graal - I'm not sure if that's the case or not.

Your question about Sulong and IR doesn't really match up with what you want. It's the LLVM backend that emits the instructions you want, not the LLVM IR. We don't use the LLVM backend so what it manages to do doesn't help you here.

**Comment by richardstartin** [comment]
@chrisseaton

Thanks for your input. I hasten to add I’m not a compiler expert, hence a slightly muddled question. What I’m asking about is precisely how to generate and invoke arbitrary snippets of assembly, which you have addressed. Knowing a bit more about the purpose of the sulong project, this wasn’t the best place to ask.
