### ISSUE TITLE
Truffle issues with JAVA_HOME including spaces

### ISSUE THREAD

**Issue by tjoyal** [graalvm/sulong#832]
New to Truffle I hit few corner-cases that slowed me down and this was one of them.

This is my setup:
```
$ echo $JAVA_HOME
/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home
```

Within walls of text I was getting:
```
Building com.oracle.truffle.llvm.asm.amd64.parser with GNU Make... [rebuild needed by GNU Make]
/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -jar /Users/tjoyal/.mx/cache/COCO_f204783009ab88838b5118adce58eca4368acd94.jar -package com.oracle.truffle.llvm.asm.amd64 -o ../com.oracle.truffle.llvm.asm.amd64/src/com/oracle/truffle/llvm/asm/amd64 ../com.oracle.truffle.llvm.asm.amd64/src/InlineAssembly.atg
make: /Applications/Android: No such file or directory
/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -jar /Users/tjoyal/.mx/cache/COCO_f204783009ab88838b5118adce58eca4368acd94.jar -package com.oracle.truffle.llvm.asm.amd64 -o ../com.oracle.truffle.llvm.asm.amd64/src/com/oracle/truffle/llvm/asm/amd64 ../com.oracle.truffle.llvm.asm.amd64/src/InlineAssembly.atg
make: /Applications/Android: No such file or directory
make: *** [../com.oracle.truffle.llvm.asm.amd64/src/com/oracle/truffle/llvm/asm/amd64/Parser.java] Error 1
make: *** Waiting for unfinished jobs....
make: *** [../com.oracle.truffle.llvm.asm.amd64/src/com/oracle/truffle/llvm/asm/amd64/Scanner.java] Error 1
```

I tried to fix it in `projects/com.oracle.truffle.llvm.pipe.native/Makefile` and `projects/com.oracle.truffle.llvm.asm.amd64.parser/Makefile` but my makefile-fu is just not that good to come to a clean solution.

I'll let you decide if it is worth fixing, to give a clear unsupported error message or to simply close it.

**Comment by jkreindl** [comment]
Until this issue is fixed you may want to use a JDK on a supported path. You can set `JAVA_HOME` and any other environment variables for the build process in `mx.sulong/env`.

It looks like you are using a JDK that came with Android Studio. If you want to get good performance out of Sulong you will need to use [the Graal compiler](https://github.com/oracle/graal/tree/master/compiler). That requires a JVMCI-enabled JDK (as available from [the GraalVM Website](http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html)) in any case.

**Comment by rschatz** [comment]
That should be easy to fix. I'll look into that.
